main:
  - identifier: booking
    weight: 10
    pageRef: "booking"
    params:
      icon:
        vendor: fas
        name: hotel

  - identifier: tourism
    weight: 20
    pageRef: "tourism"
    params:
      icon:
        vendor: mdi
        name: plane-car
        width: 1.4em
        height: 1.4em

  - identifier: medical
    weight: 20
    pageRef: "medical"
    params:
      icon:
        vendor: mdi
        name: doctor
        width: 1.4em
        height: 1.4em

  - identifier: rental
    weight: 30
    pageRef: "rental"
    params:
      icon:
        # vendor: fas
        # name: "money-check-dollar"
        # vendor: fas
        # name: "money-bill-trend-up"
        # vendor: tabler
        # name: "outline/report-money"
        vendor: tabler
        name: "outline/cash-register"
        # name: "outline/home-dollar"
        height: "1.4rem"
        width: "1.4rem"

  - identifier: renovation
    weight: 40
    pageRef: "renovation"
    params:
      icon:
        # vendor: mdi
        # name: home-flood
        vendor: tabler
        name: outline/home-eco
        width: 1.4em
        height: 1.4em

  - identifier: divider-main-contact
    weight: 900
    params:
      divider: true

  - identifier: contact
    weight: 1000
    pageRef: "contact"
    params:
      header: contact_header
      columns: 1
      icon:
        vendor: font-awesome-solid
        name: headset

  - identifier: whatsapp
    name: WhatsApp
    parent: contact
    url: https://wa.link/uelcmg
    weight: 10
    params:
      icon:
        vendor: fab
        name: whatsapp
        color: green
      description: whatsapp_desc

  - identifier: facebook
    name: Facebook
    parent: contact
    url: https://www.facebook.com/bait.gameel/
    weight: 20
    params:
      icon:
        vendor: fab
        name: facebook
        color: blue
      description: facebook_desc

  - identifier: instagram
    name: Instagram
    parent: contact
    url: https://www.instagram.com/bait.gameel
    weight: 30
    params:
      icon:
        vendor: fab
        name: instagram
        color: "#c03957"
      description: instagram_desc

  - identifier: youtube
    name: YouTube
    parent: contact
    url: https://www.youtube.com/@bait.gameel
    weight: 40
    params:
      icon:
        vendor: fab
        name: youtube
        color: red
      description: youtube_desc

  - identifier: divider-contact
    parent: contact
    weight: 50
    params:
      divider: true

  - identifier: sendemail
    parent: contact
    url: "mailto:h.h.egypt@baitgameel.com"
    weight: 60
    params:
      icon:
        vendor: mdi
        name: email-fast-outline
        # color: red
      description: sendmail_desc

  - identifier: call
    parent: contact
    url: "tell:+971-501896163"
    weight: 70
    params:
      icon:
        vendor: tabler
        name: outline/phone-call
        # color: red
      description: +971-501896163
