
hb:
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  full_width: true # when true, the layout takes full width globally.
  logo: "header-logo.png"
  # full_width: true

  progress_bar:
    height: '4px'
    initial_width: 20
    interval: 50
    time: 2

  header:
    # logo: false
    # logo_bg: '#712cf9' # logo background color, used by logo with transparent background.

    banner:
      img: "/images/banners/home.webp"
      transparentize_navbar_bg : false
      alignment: "start"
      color: "#fff"

    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      # _color: true # when false, remove the color of social icons.
      facebook: bait.gameel
      youtube: "https://www.youtube.com/@bait.gameel"
      instagram: bait.gameel
      email: h.h.egypt@baitgameel.com
      tel: "+971-501896163"
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      facebook: bait.gameel
      youtube: "https://www.youtube.com/@bait.gameel"
      instagram: bait.gameel
      email: h.h.egypt@baitgameel.com
      tel: "+971-501896163"
  blog:
    list_cols_md: 3
    list_cols_lg: 4
    toc:
      position: end
    social_share_buttons:
      alignment: center
      media:
        - twitter
        - facebook
        - linkedin
        # - sinaweibo
    sidebar:
      sticky: true # set it to false to not stick the sidebar.
      width: .2 # the width of sidebar.
      position: start # the sidebar position: start (left) or end (right).
      profile:
        avatar_size: 100
        socials:
          facebook: bait.gameel
          youtube: "https://www.youtube.com/@bait.gameel"
          instagram: bait.gameel
          email: h.h.egypt@baitgameel.com
          tel: "+971-501896163"
      posts:
        recent_count: 0 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
        style: pills # pills, tabs or underline.
        list_style: vertical # slide or vertical.
    # paginate: 12 # paginate.
    post_thumbnail_placeholder: Bait Gameel # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 0 # the number of the featured posts, 0 means disabled.
      pinned_posts_position: "list"
      main_sections: # leave it empty to include all regular pages.
        # - docs
        - blog
        - news
    giscus:
      repo: hbstack/theme-cards
      repo_id: R_kgDOK1LmSQ
      category_id: DIC_kwDOK1LmSc4CbdiM
  docs:
    giscus:
      repo: hbstack/theme-cards
      repo_id: R_kgDOK1LmSQ
      category_id: DIC_kwDOK1LmSc4CbdiM
    social_share_buttons:
      alignment: center
      media:
        - twitter
        - facebook
        - linkedin
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: hbstack/theme-cards
      branch: main
      subpath: exampleSite
  # gallery:
  #   thumbnail_size: "x640"
  # google_fonts:
    # families:
      # - name: Lato

seo:

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
# pwa:
#   debug: false
#   manifest:
#     background_color: '#33185c'
#     theme_color: '#33185c'
#     short_name: 'Bait Gameel'

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 4
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
