description: "Unlock a new vision of Egypt with our luxurious, affordable rentals and unforgettable tours. Property owners can maximize profits with our tailored rental and renovation packages."

hb:
  header:
    brand: Bait Gameel # the brand name, leave it empty to use site's title.
    banner:
      title: |
        Innovation Meets Hospitality, New Vision for Modern Egypt Travel
        { data-aos="fade-down" data-aos-delay="200" style="background: #33185ccc; padding: 1rem" }
      description: |
        With our innovative approach to rentals and tours, BaitGameel is your gateway to exploring Egypt in style and comfort. Whether you’re a traveler seeking comfort or an owner looking to grow your income, BaitGameel is your trusted partner.
        { data-aos="fade-up" data-aos-delay="300" style="background: #33185ccc; padding: 1rem" }
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
  blog:
    sidebar:
      profile:
        title: Bait Gameel
        # description: Profile description other than site description.
        # company: Bait Gameel
        # location: Dubai

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  manifest:
    short_name: 'Bait Gameel'
