classes = [
    "row",
    "col-md-1", "col-md-2", "col-md-3", "col-md-4", "col-md-5", "col-md-6", "col-md-7", "col-md-8", "col-md-9", "col-md-10", "col-md-11", "col-md-12",
    "col-sm-1", "col-sm-2", "col-sm-3", "col-sm-4", "col-sm-5", "col-sm-6", "col-sm-7", "col-sm-8", "col-sm-9", "col-sm-10", "col-sm-11", "col-sm-12",
    "col-lg-1", "col-lg-2", "col-lg-3", "col-lg-4", "col-lg-5", "col-lg-6", "col-lg-7", "col-lg-8", "col-lg-9", "col-lg-10", "col-lg-11", "col-lg-12",
    "col-xl-1", "col-xl-2", "col-xl-3", "col-xl-4", "col-xl-5", "col-xl-6", "col-xl-7", "col-xl-8", "col-xl-9", "col-xl-10", "col-xl-11", "col-xl-12",
    "col-1", "col-2", "col-3", "col-4", "col-5", "col-6", "col-7", "col-8", "col-9", "col-10", "col-11", "col-12",
    "d-flex",
    "justify-content-start", "justify-content-end", "justify-content-center", "justify-content-between", "justify-content-around", "justify-content-evenly",
    "fw-bold", "fw-light", "fw-normal", "fw-semibold", "fw-bolder",
    "badge", "badge-primary", "badge-secondary", "badge-success", "badge-danger", "badge-warning", "badge-info", "badge-light", "badge-dark",
    "text-bg-dark", "text-bg-primary", "text-bg-secondary", "text-bg-success", "text-bg-danger", "text-bg-warning", "text-bg-info", "text-bg-light",
    "my-0", "my-1", "my-2", "my-3", "my-4", "my-5", "my-auto",
    "text-success", "text-primary", "text-secondary", "text-danger", "text-warning", "text-info", "text-light", "text-dark", "text-muted", "text-white",
    "alert", "alert-primary", "alert-secondary", "alert-success", "alert-danger", "alert-warning", "alert-info", "alert-light", "alert-dark",
    "align-items-start", "align-items-end", "align-items-center", "align-items-baseline", "align-items-stretch",
    "bi",
    "flex-shrink-0", "flex-shrink-1",
    "me-0", "me-1", "me-2", "me-3", "me-4", "me-5", "me-auto",
    "carousel", "carousel-item", "carousel-inner", "carousel-indicators", "carousel-control-prev", "carousel-control-next",
    "carousel-control-prev-icon", "carousel-control-next-icon",
    "visually-hidden",
    "active",
    "lazyloaded"
]
ids = []
tags = []
attributes = []
safelist_deep = []
safelist_greedy = []
safelist_standard = []
